language: perl

perl:
  - "blead"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - cpanm --notest Devel::Cover::Report::Coveralls
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 SKIP_POD_LINKCHECK=1
  - git submodule update --init --recursive

install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla~5 Dist::Zilla::Plugin::PodWeaver Test::Spelling
  - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
  - "dzil listdeps --missing | cpanm --quiet --notest"

script:
  perl Makefile.PL build && cover -test

after_success:
  cover -report coveralls

notifications:
  email:
    recipients:
      - autarch@urth.org
    on_success: change
    on_failure: always
